spring:
  application:
    name: barbersync
  datasource:
    url: jdbc:postgresql://localhost:5433/barbersync_db_test
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
    key: ${PASS_JWT}

server:
  port: 8085
  servlet:
    context-path: /api/v1

springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs
    deepLinking: true
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1